print("holash")
print("ahora hago el tercer commit pero en una rama nueva")
print("ahor hago un nuevo commit en esta rama, haciendo que sea el segundo de la misma")
print("empiezo a usar GitKraken")
print("estamos en una nueva rama donde se supone que solucionamos un bug")
print("hicimos merge entre las rama fix y la rama1 y ahora lo hago entre la rama1 y master")